server {
    listen 80;
    server_name b.kktaskpaas.com;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;  # 去掉 http2
    server_name b.kktaskpaas.com;

    ssl_certificate /etc/letsencrypt/live/b.kktaskpaas.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/b.kktaskpaas.com/privkey.pem;

    # 添加这些基本的 SSL 参数
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass http://127.0.0.1:8890;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}